telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 22, in greet_user
    print(upfate)
NameError: name 'upfate' is not defined
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 22, in greet_user
    print(upfate)
NameError: name 'upfate' is not defined
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - WARNING - Exiting immediately!
